"""Generic ASE-calculator engine for vasp-auto.

This is the ``engine: ase`` backend. Instead of writing VASP (INCAR/KPOINTS/
POTCAR) or QE (pw.in) inputs, it prepares a small, self-contained driver script
``run_ase.py`` in the job directory that:

  1. reads the case ``POSCAR`` with ASE,
  2. attaches a named ASE calculator (chosen in config; see ``CALC_REGISTRY``),
  3. runs a single-point energy (``scf``) or a BFGS relaxation (``relax``),
  4. writes ``CONTCAR`` (final structure) and ``ase_results.json`` (the parse
     contract, mirroring how ``pw.out`` is QE's contract).

One integration unlocks every code ASE can drive (EMT, Lennard-Jones, Quantum
ESPRESSO, GPAW, ABINIT, CASTEP, SIESTA, NWChem, an ASE-driven VASP, MLIPs …):
the user names the calculator and points at its binary via ``ase_calc_params``.
``emt`` is the default and needs no external binary, so it also makes the engine
testable end-to-end.

Config keys (global/project/case ``config.yaml``):
  ase_calculator:  registry name, e.g. "emt", "espresso", "gpaw"   (default "emt")
  ase_calc_params: dict of keyword args passed to the calculator    (default {})
                   (special keys __module__/__class__ override the registry)
  ase_fmax:        force tolerance for relax, eV/A                   (default 0.05)
  ase_steps:       max optimizer steps for relax                    (default 200)
  ase_python:      python that runs the driver                      (default: the
                   interpreter running vasp-auto)
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

# calc-types this engine understands today (mirrors QE's limited scope).
ASE_SUPPORTED_CALC_TYPES = ("scf", "relax")

# Named ASE calculators the driver's CALC_REGISTRY knows out of the box (for the
# CLI/GUI to offer as a menu). Anything else is reachable via the special params
# __module__ / __class__. Keep in sync with CALC_REGISTRY in ASE_DRIVER below.
ASE_CALCULATORS = (
    "emt", "lj", "morse", "espresso", "gpaw", "abinit",
    "castep", "siesta", "nwchem", "vasp", "dmol3", "mace",
)

# Driver script written into every ASE job directory. Standalone — it depends
# only on ASE + numpy and reads its settings from ase_calc.json next to it, so a
# job directory can be shipped/rerun without vasp_auto on PYTHONPATH.
ASE_DRIVER = '''#!/usr/bin/env python3
"""Auto-generated by vasp-auto (engine: ase). Runs an ASE calculator on POSCAR
and writes ase_results.json. Depends only on ase + numpy."""
import importlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# name -> (module, class) for ASE calculators. Override per-job with the special
# params __module__ / __class__ to reach any calculator not listed here.
CALC_REGISTRY = {
    "emt": ("ase.calculators.emt", "EMT"),
    "lj": ("ase.calculators.lj", "LennardJones"),
    "morse": ("ase.calculators.morse", "MorsePotential"),
    "espresso": ("ase.calculators.espresso", "Espresso"),
    "gpaw": ("gpaw", "GPAW"),
    "abinit": ("ase.calculators.abinit", "Abinit"),
    "castep": ("ase.calculators.castep", "Castep"),
    "siesta": ("ase.calculators.siesta", "Siesta"),
    "nwchem": ("ase.calculators.nwchem", "NWChem"),
    "vasp": ("ase.calculators.vasp", "Vasp"),
    "dmol3": ("ase.calculators.dmol", "DMol3"),
    "mace": ("mace.calculators", "MACECalculator"),
}


def make_calculator(spec):
    name = (spec.get("calculator") or "emt").lower()
    params = dict(spec.get("params") or {})
    mod = params.pop("__module__", None)
    cls = params.pop("__class__", None)
    if not (mod and cls):
        if name not in CALC_REGISTRY:
            raise SystemExit(
                "Unknown ASE calculator %r. Known: %s "
                "(or set params.__module__ and params.__class__)."
                % (name, sorted(CALC_REGISTRY))
            )
        mod, cls = CALC_REGISTRY[name]
    module = importlib.import_module(mod)
    return getattr(module, cls)(**params)


def main():
    import numpy as np
    from ase.io import read, write

    spec = json.loads((HERE / "ase_calc.json").read_text())
    calc_type = spec.get("calc_type", "scf")
    atoms = read(HERE / "POSCAR", format="vasp")
    atoms.calc = make_calculator(spec)
    print("ASE engine: %s | calc_type=%s | %d atoms"
          % (spec.get("calculator"), calc_type, len(atoms)), flush=True)

    converged = True
    ionic_steps = 1
    if calc_type == "relax":
        from ase.optimize import BFGS
        fmax = float(spec.get("fmax", 0.05))
        steps = int(spec.get("steps", 200))
        opt = BFGS(atoms, logfile="-", trajectory=str(HERE / "ase.traj"))
        opt.run(fmax=fmax, steps=steps)
        ionic_steps = opt.get_number_of_steps()
        fmax_now = float(np.sqrt((atoms.get_forces() ** 2).sum(axis=1).max()))
        converged = fmax_now <= fmax

    energy = float(atoms.get_potential_energy())
    forces = atoms.get_forces()
    max_force = float(np.sqrt((forces ** 2).sum(axis=1).max()))

    write(HERE / "CONTCAR", atoms, format="vasp")
    results = {
        "engine": "ase",
        "calculator": spec.get("calculator"),
        "calc_type": calc_type,
        "energy_eV": energy,
        "max_force_eV_A": max_force,
        "ionic_steps": ionic_steps,
        "converged": bool(converged),
    }
    (HERE / "ase_results.json").write_text(json.dumps(results, indent=2))
    print("Energy    : %.6f eV" % energy, flush=True)
    print("Max force : %.4f eV/A   converged=%s" % (max_force, converged), flush=True)
    print("ASE_DONE", flush=True)


if __name__ == "__main__":
    main()
'''


def _ase_spec_from_config(config: dict, calc_type: str) -> dict:
    """The settings the driver needs, distilled from config."""
    return {
        "calculator": (config.get("ase_calculator") or "emt"),
        "params": dict(config.get("ase_calc_params") or {}),
        "calc_type": calc_type,
        "fmax": float(config.get("ase_fmax", 0.05)),
        "steps": int(config.get("ase_steps", 200)),
    }


def _check_calc_type(calc_type: str) -> str:
    if calc_type not in ASE_SUPPORTED_CALC_TYPES:
        raise ValueError(
            f"ASE engine does not support calc-type '{calc_type}'. "
            f"Supported: {', '.join(ASE_SUPPORTED_CALC_TYPES)}."
        )
    return calc_type


def create_ase_job(
    case_info: dict,
    config: dict,
    *,
    calc_type: str | None = None,
    kpoints_spec: dict | None = None,
    spin: bool = False,
    magmom_map: dict | None = None,
) -> Path:
    """Prepare an ASE job directory (POSCAR + ase_calc.json + run_ase.py + .engine)."""
    case_dir = Path(case_info["case_dir"]).resolve()
    job_dir = Path(case_info["job_dir"]).resolve()
    calc_type = _check_calc_type(calc_type or case_info.get("calculation_type") or "scf")

    poscar = case_dir / "POSCAR"
    if not poscar.exists():
        raise FileNotFoundError(f"No POSCAR in {case_dir}")

    job_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(poscar, job_dir / "POSCAR")

    spec = _ase_spec_from_config(config, calc_type)
    (job_dir / "ase_calc.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
    (job_dir / "run_ase.py").write_text(ASE_DRIVER, encoding="utf-8")
    (job_dir / ".engine").write_text("ase\n", encoding="utf-8")
    return job_dir


def preview_ase_job(
    case_info: dict,
    config: dict,
    *,
    calc_type: str | None = None,
    kpoints_spec: dict | None = None,
    spin: bool = False,
    magmom_map: dict | None = None,
) -> dict:
    """Return the ASE input set as a dict without writing anything (dry-run/GUI)."""
    case_dir = Path(case_info["case_dir"]).resolve()
    calc_type = _check_calc_type(calc_type or case_info.get("calculation_type") or "scf")
    spec = _ase_spec_from_config(config, calc_type)
    return {
        "case_name": case_info["case_name"],
        "calculation_type": case_info.get("calculation_type", "scf"),
        "calc_type": calc_type,
        "engine": "ase",
        "job_dir": str(case_info["job_dir"]),
        "POSCAR": str(case_dir / "POSCAR"),
        "calculator": spec["calculator"],
        "ase_calc.json": json.dumps(spec, indent=2),
        "run_ase.py": ASE_DRIVER,
    }


def parse_ase_output(job_dir: str | Path) -> dict | None:
    """Read ase_results.json into a summary dict (None if the run never finished)."""
    job_dir = Path(job_dir)
    results_file = job_dir / "ase_results.json"
    if not results_file.exists():
        return None
    try:
        return json.loads(results_file.read_text(encoding="utf-8"))
    except (ValueError, OSError):
        return None
